# Generated by Django 3.2.7 on 2021-10-01 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_transplant', models.BooleanField(default=False)),
                ('pregnancy', models.BooleanField(default=False)),
                ('cardiovascular_disease', models.BooleanField(default=False)),
                ('COPD', models.BooleanField(default=False)),
                ('renal_disease', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_disease', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChronicDisease',
                'verbose_name_plural': 'ChronicDiseases',
            },
        ),
    ]
