# Generated by Django 3.2.7 on 2021-10-01 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicdisease',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chronic_disease', to=settings.AUTH_USER_MODEL),
        ),
    ]
