# Generated by Django 3.2.7 on 2021-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_chronicdisease_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicdisease',
            name='COPD',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='cancer',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='cardiovascular_disease',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='organ_transplant',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='chronicdisease',
            name='renal_disease',
        ),
        migrations.AddField(
            model_name='chronicdisease',
            name='name',
            field=models.CharField(choices=[('organ_transplant', 'Organ Transplan'), ('pregnancy', 'Pregnancy'), ('cardiovascular_disease', 'Cardiovascular Disease'), ('COPD', 'COPD'), ('renal_disease', 'Renal disease'), ('cancer', 'Cancer'), ('hypertension', 'Hypertension'), ('diabetes', 'Diabetes')], default='organ_transplant', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chronicdisease',
            name='severty',
            field=models.DecimalField(decimal_places=4, default=2.4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='chronic_diseases',
            field=models.ManyToManyField(blank=True, null=True, related_name='owner', to='user.ChronicDisease'),
        ),
    ]
