# Generated by Django 3.2.7 on 2021-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211002_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chronicdisease',
            old_name='severty',
            new_name='severity',
        ),
    ]
